const PLANNED_TERM_OPTIONS = {
  "": { year: "" },

  1253: { year: "Mid 2026" },
  1261: { year: "1st 2026-2027" },
  1262: { year: "2nd 2026-2027" },

  1263: { year: "Mid 2027" },
  1271: { year: "1st 2027-2028" },
  1272: { year: "2nd 2027-2028" },

  1273: { year: "Mid 2028" },
  1281: { year: "1st 2028-2029" },
  1282: { year: "2nd 2028-2029" },

  1283: { year: "Mid 2029" },
  1291: { year: "1st 2029-2030" },
  1292: { year: "2nd 2029-2030" },
};

const HK_TYPE_OPTIONS = [
  "",
  "Aerobic Dancing",
  "Aikido",
  "Arnis",
  "Asian Dance",
  "Archery",
  "Ballet for Beginners",
  "Basketball",
  // "Basketball Female",
  // "Basketball Male",
  "Billiards",
  "Belly Dancing",
  "Baseball",
  "Badminton",
  "Beach Volleyball",
  // "Beach Volleyball (COED)",
  "Contract Bridge Game",
  "Contemporary Dance",
  "Chess",
  "Cheer Dance",
  "Cardio Kung Fu",
  "Duckpin Bowling",
  "DanceSport",
  "Darts",
  "Football/Soccer",
  // "Football (COED)",
  // "Football/Soccer for female",
  // "Football/Soccer for male",
  "Female Handball",
  "Futsal",
  // "Futsal (Indoor Football)",
  // "Futsal for female",
  // "Futsal for male",
  "Hawaii",
  "Hoof Dance",
  "Hooping Fitness",
  "Hula/Tahitian",
  "Judo",
  "Karatedo",
  "Line Dance",
  "Lawn Tennis",
  "Laughter Yoga",
  "Modern Dance",
  "Male Handball",
  "Modern Jazz",
  "Muslim Dance",
  "Neo-Filipino",
  "Outdoor Recreation",
  "Pickle Ball",
  "Philippine Folk Dance",
  "Philippine Game",
  "Pilates",
  "Polynesian Dance",
  "Running for Fitness",
  "Roper Flow",
  "Social Dance",
  "Self-Defense",
  "Softball",
  // "Softball Female",
  // "Softball Male",
  "Shakti",
  "Street Jazz",
  "Slo-Pitch Softball",
  "Sepak takraw",
  "Stretching",
  "Swimming",
  // "Swimming (COED)",
  // "Swimming Female",
  // "Swimming Male",
  "Tai-chi-chuan",
  "Tap Dance",
  "Track & Field",
  "Taekwondo",
  "Table Tennis",
  "Ultimate Frisbee",
  "Volleyball",
  // "Volleyball Female",
  // "Volleyball Male",
  "Woodball",
  "Walking for Fitness",
  "Weight Training",
  // "Weight Training (COED)",
  "Yoga",
  "Zumba",
];

const HK_NSTP_REQUIREMENTS = [
  { code: "HK 11", required: 1, needsType: false },
  { code: "HK 12", required: 3, needsType: true },
  { code: "NSTP 1", required: 1, needsType: false },
  { code: "NSTP 2", required: 1, needsType: false },
];
